import Link from 'next/link';
import { PageHero } from '@/components/site/page-hero';
import { createClient } from '@/lib/supabase/server';

export const metadata = { title: 'Scholarships', description: 'Scholarship opportunities for Afghan students in Malaysia.' };

export default async function ScholarshipsPage() {
  const { data, error } = await createClient().from('scholarships').select('id,title,provider,description,eligibility,deadline,amount,application_url,image_url').eq('status','published').order('deadline',{ascending:true,nullsFirst:false}).range(0,99);
  return <><PageHero eyebrow="Scholarships" title="Scholarship opportunities" description="Explore scholarship opportunities published for the ASAM community."/><section className="py-10"><div className="container mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">{error&&<p role="status" className="rounded-lg bg-amber-50 p-4 text-sm text-amber-900">Scholarship information is temporarily unavailable.</p>}{data?.length?<div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{data.map((item)=><article key={item.id} className="overflow-hidden rounded-xl border border-border bg-card shadow-premium">{item.image_url&&<img loading="lazy" src={item.image_url} alt="" className="aspect-[16/9] w-full object-cover"/>}<div className="p-6"><p className="text-xs font-bold uppercase tracking-wider text-gold-dark">{item.provider||'Scholarship'}</p><h2 className="mt-2 font-display text-xl font-bold">{item.title}</h2>{item.amount&&<p className="mt-2 text-sm font-semibold">Amount: {item.amount}</p>}{item.deadline&&<p className="mt-1 text-xs text-muted-foreground">Deadline: {new Date(`${item.deadline}T00:00:00`).toLocaleDateString()}</p>}<p className="mt-4 whitespace-pre-wrap text-sm leading-relaxed text-muted-foreground">{item.description}</p>{item.eligibility&&<p className="mt-3 text-sm"><b>Eligibility:</b> {item.eligibility}</p>}{item.application_url&&((item.application_url.startsWith('/')&&!item.application_url.startsWith('//'))||/^https:\/\//i.test(item.application_url))&&<Link href={item.application_url} target={/^https:\/\//i.test(item.application_url)?'_blank':undefined} rel={/^https:\/\//i.test(item.application_url)?'noreferrer':undefined} className="mt-5 inline-flex rounded-lg bg-navy px-4 py-2.5 text-sm font-semibold text-white">Application details</Link>}</div></article>)}</div>:!error&&<div className="rounded-xl border border-dashed p-12 text-center"><h2 className="font-display text-xl font-semibold">No published scholarships yet</h2><p className="mt-2 text-sm text-muted-foreground">New opportunities will appear here when confirmed by ASAM.</p></div>}</div></section></>;
}
